name: Greetings

on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GHUB_TOKEN }}
        pr-message: "Message that will be displayed on users' first pull request"
